### ISSUE TITLE
Implement CompositeLink

### ISSUE THREAD

**Issue by scgruber** [route-rs/route-rs#109]
This is a link that can contain a big collection of many elements/links on the inside.

Should have PacketStreams as input & output. Needs to provide all internal task handles for tokio.

**Comment by ddowl** [comment]
Since it's been a hot second since I've thought about this, maybe we should clarify the use cases and interface? The idea is that a small network of links can be created-inside/passed-into to a `CompositeLink` which abstracts away the details of the network. In the one-to-one case, it should take an ingress `PacketStream` as a source for the network and expose an egress `PacketStream`.

Some open questions that might be nice to nail down before starting implementation are:

Interface Qs:
- Internal `Link`s should be connected before being passed into a `CompositeLink`, so they could be passed in as a `Vec<L: EveryLinkType>`, since the network could contain any possible `Link` type. How do we type this input collection? Do we need to maintain a union type of all `Link`s we ever create and ensure that our `CompositeLink` knows how to handle them? The primary purpose of typing the `Link` collection will be to collect references to task handles so the caller of `CompositeLink` can invoke Tokio. As of now, this applies to `AsyncLink`, `ClassifyLink`, `CompositeLink`, `JoinLink`, and `TeeLink`, but doesn't apply to `BlackholeLink`, and `SyncLink`. A potential solution could be to implement a trait `TokioRunnable` that has a function `tasks() -> Vec<Task>` so each link can specify all of the tasks that should be handed to Tokio in order to run. We could have a marker trait `Link` where some of them can be `TokioRunnable`? 
- Since the purpose of the `CompositeLink` is to abstract a more complicated network of links, I imagine black boxes of many-ingress/many-egress `PacketStream`s appearing. How should we present them to clients of `CompositeLink`? `Vec<PacketStream>` isn't terrible since we can at least provide ordering as a method of determining what the Stream refers to, but I already feel like I'm doing mental gymnastics when I wire these things together.

Use Case Qs:
- I remember us talking about renaming `Pipeline` to `Router`, which takes an input/output channel to the actual ingress/egress of the network as well as 1 or more `CompositeLink`s. which can be defined independently of the `Router`.
- If clients want to share `Element`s, that's already pretty easy. Just `impl Element` or `AsyncElement` on your struct and your good to go. But if someone comes up with a cool network feature they want to share (e.g. a NAT implementation), what's the best way they can share that? This ties back to the `Link` typing question above. If a user creates some new network feature and uses a `CompositeLink` to store it, how does our code know how to work with it?

```
struct NATLink {
  links: CompositeLink
}

impl NATLink {
  pub fn new(...) -> Self {
    // wire together a bunch of leaf links here in a cool way
    ...
    NATLink {
      links: CompositeLink::new(...)
    }
  }
}
```

Since `NatLink` doesn't conform to any particular trait, how will we know that there's a `CompositeLink` inside and get its runnable `Task`s for tokio?

**Comment by CollinValley** [comment]
Yeah this does bring up an interesting question. Because the concept of `CompositeLink` really only makes sense in the context that it contains a subset of wired together and loaded links. Wired together meaning the links are linked up, and loaded meaning that each internal link contains the elements required to make it do something useful. In the case of the NATLink, the internal links will need elements preloaded otherwise the whole concept kind of falls apart. Maybe we should change the name back to pipeline,  make Pipeline a trait, that to satisfy you implement your own new function. Which creates, loads, and wires links, and then returns a `Vec<TokioTasks>`, plus some object that functions as the ingressor and egressor to wire more stuff to.  This warrants further in person discussion I think.

**Comment by ddowl** [comment]
Discussed offline, we'd like to support a `Link<A, B>` trait which all `*Link` objects can implement which will allow them to be composed.

This would look something like: 
```
trait Link<A, B> {
  fn new<A>(ingress_streams: Vec<PacketStream<A>>) -> Self
  fn runnbales() -> Vec<Future<()>>
  fn egressors() -> Vec<PacketStream<B>>
}
```

`SyncLink` and `AsyncLink` also need a way to get an `Element` or `AsyncElement` to it, so they will need:

```
trait ElementLink<E>: Link<E::Input, E::Output> {
  fn element<E>(element: E) -> Self
}
```

`ClassifyLink` is weird and will need a few other functions as well:
```
trait ClassifierLink<C>: Link<C::Packet, C::Packet> {
  fn classifier<C>(classifier: C) -> Self
  fn dispatcher(Fn(C::Class) -> usize) -> Self
} 
```

**Comment by CollinValley** [comment]
Let's park, but not close, this issue pending completion of changing the runtime over from our current impl to the trait driven one.

**Comment by CollinValley** [comment]
Made the first composite and merged it.  The M to N and M transform N options.
