### ISSUE TITLE
Testing Utilities/Framework

### ISSUE THREAD

**Issue by ddowl** [route-rs/route-rs#12]

**Comment by CollinValley** [comment]
I think there are a number of low hanging fruit we could attack first on this:

1.  Move the test suites next to their implementations, and maybe only leave a few examples in the head of the library.
2. Clean up some tests that are redundant at this point.  (I don't think we need to neccesarily use all the generators on an implementation to assert that it is correct,  example the immediate yield, interval yield)
3. Pivot the test names to reflect what they are testing about the implementation rather than the fixtures used.  For instance we should have a test that ensures the AsyncElementConsumer can sleep and be awoken, same for provider.  We should make sure we have a test where the threadpool is 1, and where the threadpool is many so we have the Consumer and Provider running in parallel.
4. Add comments to each test detailing what it tests and why it is important.
