### ISSUE TITLE
Investigate state tracking elements/actors/agents.

### ISSUE THREAD

**Issue by ddowl** [route-rs/route-rs#13]
do client ip table?

**Comment by CollinValley** [comment]
I've spent some time on this.  I've tried a few different things but they all end up being thin wrappers on RWLock<Hashmap<>>.  I would rather wait on this until we are trying to implement a POC, and let the structures we need to store state naturally percolate out.  Element implementors can embed ARCs to whatever common state things they need. And what data structure they need under the hood should be educated by the access pattern.  We will, in making our PoC create some basic ones that are good defaults, so users of the library don't need to think too hard. But I don't think this issue is at the runtime level. The exception to this would be if we created an actual actor for something with a mailbox and such.  We will need a special state actor created by the runtime, but we should wait until we need it so we don't engineer a solution for the wrong problem.  WIll bring this up at today's meetup before closing this issue.
